services:

  traefik:
    image: "traefik:v3.6"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/docker/traefik/certs:/certs:ro
    networks:
      - symfony

  apache:
    build: ${PWD}/docker/apache
    user: "${UID}:${GID}"
    container_name: ${PROJECT_NAME}-apache
    restart: unless-stopped
    volumes:
      - ${PWD}/docker/apache/symfonydesk.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ${PWD}/site:/var/www/symfonydesk
      - ${PWD}/docker/apache/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${PROJECT_NAME}.docker.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-http.middlewares=${PROJECT_NAME}-redirect"
      - "traefik.http.middlewares.${PROJECT_NAME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${PROJECT_NAME}-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.${PROJECT_NAME}-https.rule=Host(`${PROJECT_NAME}.docker.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-https.tls=true"
    networks:
      - symfony
    working_dir: /var/www/symfonydesk

  db:
    image: mysql:8.1
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfonydesk
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  mailer:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}-mailer
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  db_data:
  traefik_certs:

networks:
  symfony:
    driver: bridge


